trigger:
  tags:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: pack
    projects: 'GitHubLabelSetUpper/*.csproj'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Build.SourceBranchName'
    outputDir: '$(Build.ArtifactStagingDirectory)'
# cannot use DotNetCoreCLI@2 command, because its command cannot use encrypted API Key
- task: NuGetCommand@2
  inputs:
    command: push
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    externalEndPoint: 'nugetConnection'
