trigger:
  - master

pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
   command: test
   publishTestResults: true
   configuration: '$(buildConfiguration)'
